### ISSUE TITLE
Issue about glue_lora.sh

### ISSUE THREAD

**Issue by Colin-chan1366** [HanGuo97/lq-lora#8]
Hi Guo,

Hopes everything goes well with you.

I tried to run all the .sh scripts and here is the question I could not solve right now. Could you please help me out of this?

Currently running a script named glue_lora.sh. There are 4 tasks in this script, task1-4. The file output by task 1 and task 2 is "output_glue_dense_20230924_ranks64_qnli".
And task 3&4 are based on the output files of task 1 and 2 (model training weights, etc.) roberta-large.ilp.ranks-64.data-True.pth to run. But the current problem is: The files produced by task 1&2 do not contain pth file, or the codes does not include the part that converted the dense output into pth files. It leads to the error of FileNotfoundError: lErrno 2] No such file or directory: '/home/ubuntu/lg-lora/llama-2/ilp data fp32/roberta-large.ilp.ranks-64.data-True.pth. Therefore, I guess we may need to add some functions to run_glue.py to store pth file correctly.

Thanks for answering!

**Comment by HanGuo97** [comment]
Hi, thanks for reaching out.

The problem here seems to be that you need some pre-computed data (the ILP output in this case). Please download them according the [instructions](https://github.com/HanGuo97/lq-lora?tab=readme-ov-file#artifacts) here.

After that, please follow the [instructions](https://github.com/HanGuo97/lq-lora?tab=readme-ov-file#downloading-data-for-quantization) and configure the specific file paths.

At the moment, we released quite a few artifacts, but unfortunately not all of them (e.g., some files are way too big to store in HuggingFace hub). If you could let me know which of these files are missing (and are important to you), I can find a way to share them with you here.

**Comment by HanGuo97** [comment]
Just a quick follow-up. I have just uploaded the related artifact files for RoBERTa. You can find them [here](https://huggingface.co/hanguo/lq-lora/blob/main/artifacts-roberta-tmp.zip).

Also, note that after you download them, you need to specify the corresponding file paths in `models/allocation_utils_2.py` (notice the `_2` suffix).

Hope that helps, and thanks for pointing this out!

**Comment by Colin-chan1366** [comment]
Hi Guo,

Really appreciate your response. Large files and datasets cannot be uploaded, which is indeed true.

In addition, I've gone through all the model output file according to the instructions. But it seems like we missing the following files:

roberta-large.ilp.ranks-64.data-True.pth
roberta-large.ilp.ranks-64.data-False.pth
roberta-large.ilp.ranks-None.data-True.pth
roberta-large.ilp.ranks-None.data-False.pth

Llama-2-7b-hf

llama-2-7b.fisher_dict.c4.length-256.nsamples-10000.pth
llama-2-7b.fisher_dict.c4.length-512.nsamples-10000.pth
roberta-large.fisher_dict.c4.length-default.nsamples-10000.pth

Really appreciate if you could share these files. And could you please let me know your preferred method for sharing these files? 

Thanks in advance!

**Comment by HanGuo97** [comment]
Got it, thanks for letting me know.

The HuggingFace Hub repo (linked in README, and above too) should have almost everything you need. I think you can try just using `length-1024` for now. Might not be the best in all cases, but probably suffice I hope.

**Comment by Colin-chan1366** [comment]
Hi Guo! 

Thanks again for sharing the Roberta files and your time! 

Good luck to your further research and looking forward to your following excellent works.

Best!

**Comment by HanGuo97** [comment]
Glad this helps!

**Comment by rG223** [comment]
> Hi Guo!
> 
> Thanks again for sharing the Roberta files and your time!
> 
> Good luck to your further research and looking forward to your following excellent works.
> 
> Best!

Hi, Can you run glue_lora.sh normally?
I got an error: https://github.com/HanGuo97/lq-lora/issues/6#issuecomment-3036202441. It is so weird.

**Comment by HanGuo97** [comment]
(replied in the linked thread.)
